import turtle
import random
t = turtle.Turtle()
t.speed(200)
t.penup()
t.setposition(-400,250)
def stvorec(dlzka):
    t.fillcolor(f'#{random.randrange(256**3):06x}')
    t.begin_fill()
    for i in range(4):
        t.fd(dlzka)
        t.rt(90)
    t.end_fill()

def trojuholnik(dlzka):
    t.fillcolor(f'#{random.randrange(256**3):06x}')
    t.begin_fill()
    for i in range(3):
        t.fd(dlzka)
        t.rt(120)
    t.end_fill()

def dom(d):
    t.pu()
    stvorec(d)
    t.lt(60)
    trojuholnik(d)
    t.rt(60)




def domisko():
        for i in range(11):
            dom(50)
            t.penup()
            t.forward(35)
            t.right(90)
            t.forward(15)
            t.pendown()
            stvorec(20)
            t.penup()
            t.forward(10)
            t.right(90)
            t.pendown()
            t.forward(20)
            t.penup()
            t.right(90)
            t.forward(10)
            t.right(90)
            t.forward(10)
            t.right(90)
            t.pendown()
            t.forward(20)

            t.penup()
            t.backward(35)
            t.left(90)
            t.forward(50)
            t.pendown()


domisko()
t.penup()
t.setpos(-400,130)
def domisko():
        for i in range(11):
            dom(50)
            t.penup()
            t.forward(35)
            t.right(90)
            t.forward(15)
            t.pendown()
            stvorec(20)
            t.penup()
            t.forward(10)
            t.right(90)
            t.pendown()
            t.forward(20)
            t.penup()
            t.right(90)
            t.forward(10)
            t.right(90)
            t.forward(10)
            t.right(90)
            t.pendown()
            t.forward(20)

            t.penup()
            t.backward(35)
            t.left(90)
            t.forward(50)
            t.pendown()


domisko()
t.penup()
t.setpos(-400,10)
def domisko():
        for i in range(11):
            dom(50)
            t.penup()
            t.forward(35)
            t.right(90)
            t.forward(15)
            t.pendown()
            stvorec(20)
            t.penup()
            t.forward(10)
            t.right(90)
            t.pendown()
            t.forward(20)
            t.penup()
            t.right(90)
            t.forward(10)
            t.right(90)
            t.forward(10)
            t.right(90)
            t.pendown()
            t.forward(20)

            t.penup()
            t.backward(35)
            t.left(90)
            t.forward(50)
            t.pendown()

domisko()
t.penup()
t.setpos(-400,-110)
def domisko():
        for i in range(11):
            dom(50)
            t.penup()
            t.forward(35)
            t.right(90)
            t.forward(15)
            t.pendown()
            stvorec(20)
            t.penup()
            t.forward(10)
            t.right(90)
            t.pendown()
            t.forward(20)
            t.penup()
            t.right(90)
            t.forward(10)
            t.right(90)
            t.forward(10)
            t.right(90)
            t.pendown()
            t.forward(20)

            t.penup()
            t.backward(35)
            t.left(90)
            t.forward(50)
            t.pendown()
domisko()
t.penup()
t.setpos(-400,-230)
def domisko():
        for i in range(11):
            dom(50)
            t.penup()
            t.forward(35)
            t.right(90)
            t.forward(15)
            t.pendown()
            stvorec(20)
            t.penup()
            t.forward(10)
            t.right(90)
            t.pendown()
            t.forward(20)
            t.penup()
            t.right(90)
            t.forward(10)
            t.right(90)
            t.forward(10)
            t.right(90)
            t.pendown()
            t.forward(20)

            t.penup()
            t.backward(35)
            t.left(90)
            t.forward(50)
            t.pendown()
domisko()
t.penup()
t.setpos(-400,-350)
def domisko():
        for i in range(11):
            dom(50)
            t.penup()
            t.forward(35)
            t.right(90)
            t.forward(15)
            t.pendown()
            stvorec(20)
            t.penup()
            t.forward(10)
            t.right(90)
            t.pendown()
            t.forward(20)
            t.penup()
            t.right(90)
            t.forward(10)
            t.right(90)
            t.forward(10)
            t.right(90)
            t.pendown()
            t.forward(20)

            t.penup()
            t.backward(35)
            t.left(90)
            t.forward(50)
            t.pendown()
turtle.mainloop()





